# Use a Node.js base image for building the React app
FROM node:20-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the frontend application files
COPY . .

# Build the Next.js application
RUN npm run build

# Expose port 3000 for the Next.js server
EXPOSE 3000

# Start Next.js
CMD ["npm", "start"]