import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import IntelligentInvestor from './component/Intelligent Investor Button/intelligentInvestor'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div>
        {/* Inside this Div will be the navbar.
        Inside the navbar, there will be two buttons: Intelligent Investor Analyzer, Sign In
        Intelligent Investor:
          When this is clicked, it'll go to the home page
        Sign In:
          If user isn't signed in, then it'll go to Sign-In Page
          If user is signed in, then this is clicked, a lil drop down will appear saying sign out. If the user
          presses that, then it'll sign out, and the content will change to sign-in. If user presses the profile
          button again, then it will undo the drop down
            If signed in, displays the user profile picture, and name as well right under it */}
          <IntelligentInvestor/>
          
      </div>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {children}
      </body>
    </html>
  );
}
