import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import IntelligentInvestor from './component/Intelligent Investor Button/intelligentInvestor'
import { cookies } from "next/headers";
import SignIn from "./component/SignIn/signIn"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*Make a GET Request to the backend for user ID. So when server-action revalidates the path, it'll pass the proper paramaters to
client component */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // You cannot call await inside JSX components, but outside is fine.
  const cookieStore = await cookies();
  const userNameVal = cookieStore.get("userName")?.value;
  const profilePictureURL = cookieStore.get("profilePictureURL")?.value;

  const authData = {
    isSignedIn: !!(userNameVal && profilePictureURL),
    userName: userNameVal || "Sign In",
    profilePicture: profilePictureURL || "",
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
              <div>
        {/* Inside this Div will be the navbar.
        Inside the navbar, there will be two buttons: Intelligent Investor Analyzer, Sign In
        Intelligent Investor:
          When this is clicked, it'll go to the home page
        Sign In:
          If user isn't signed in, then it'll go to Sign-In Page
          If user is signed in, then this is clicked, a lil drop down will appear saying sign out. If the user
          presses that, then it'll sign out, and the content will change to sign-in. If user presses the profile
          button again, then it will undo the drop down
            If signed in, displays the user profile picture, and name as well right under it 
          Initially, the Sign In component will receive no values so when you click on it, it'll take you to the sign in page
            After user goes to sign in page, and signs in through google, then it'll change the value
          */}
          <SignIn {...authData}/>
          <IntelligentInvestor/>
          
      </div>
        {children}
      </body>
    </html>
  );
}
