version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://productivity:Jxj}8}wn00@localhost:5432/productivity
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: productivity
      POSTGRES_PASSWORD: Jxj}8}wn00
      POSTGRES_DB: productivity
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
